name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: xdebug # Use xdebug for code coverage if needed

    - name: Clear Composer Cache
      run: composer clear-cache
      
    - name: Install Laravel
      run: |
        composer create-project --prefer-dist laravel/laravel laravel-app
        cd laravel-app
      
    - name: Composer install
      run: composer install --ignore-platform-reqs
      
    - name: Install Package
      run: |
        cd laravel-app
        composer require elbrahms/niger-location:"dev-master"

    - name: Copy .env
      run: |
        cd laravel-app
        php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate Application Key
      run: |
        cd laravel-app
        php artisan key:generate

    - name: Directory Permissions
      run: |
        cd laravel-app
        chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        cd laravel-app
        mkdir -p database
        touch database/database.sqlite

    - name: Publish Package Configuration
      run: |
        cd laravel-app
        php artisan vendor:publish --tag=niger-location

    - name: Run Migrations
      run: |
        cd laravel-app
        php artisan migrate --force

    - name: Seed Database
      run: |
        cd laravel-app
        php artisan db:seed --class=Elbrahms\\NigerLocation\\Database\\Seeders\\LocationDatabaseSeeder

    - name: Run Tests
      run: |
        cd laravel-app
        vendor/bin/phpunit --coverage-text
